# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 357e487ae6d1c0dc69c1c43c61b43d3a93ceb97bab169883aa27f1070c0fa34569d08f241c42cf88dd049c888e4e0b91c0cce8e4afc5508a589c45ddd564e19e
  superadmin_name: Super Admin
  superadmin_email: superadmin@admin.com
  superadmin_password: S1U2P3E4R5U6S7E8R

test:
  secret_key_base: ec143d55a5a4c0291a3447632c4f2d44e48a29cecc4cac4d7394769259b91bc84d6346f6838711bf08fb884f53d8fc0ccc0666f9fd01ad79aea5ab434a1f01ad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  superadmin_name: <%= ENV["SUPERADMIN_NAME"] %>
  superadmin_email: <%= ENV["SUPERADMIN_EMAIL"] %>
  superadmin_password: <%= ENV["SUPERADMIN_PASSWORD"] %>
